<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Menu;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menuItems = [
            // ☕ KOPI
            ['cat' => 'kopi',    'name' => 'Signature Latte',    'desc' => 'Double shot espresso dengan susu microfoam dan sentuhan vanilla.',   'price' => 55000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKbb-ii-5JXMfOSe4gnjdDxQ_ZzG7p88FeR45IwJMYs3t5ReVp-LCx87QDJ9nqNOe9fZohM04ghtFfISxa7RTJtUnM17ocevRnAsFoVw8Es7Sm2yYbflcDh5spRA3q73-n11EjRXOp4eINctb5oGeL1NnxTm1WI0Chff-2zoVE6jS7wZlw9ST9m-9RutOoqk-O295pnn9P0ZJN8JrQz4TpZSKxbbjiRNVAcvTBa-S4KRuhnbhLbzJx1cY5Al0QOAmhc5bSx5H1JlNg'],
            ['cat' => 'kopi',    'name' => 'Ethiopian Pour Over', 'desc' => 'Light roast dengan aroma floral dan citrus yang segar.',               'price' => 47500, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBT9PAG3x9TTRZJ_VWSwcirhm5GkIpO92RMRm8XMCcWuZ-QC-cA6kVJMITdAQo5QuyF9hGkqpW4hLj-N9JDujMgomkqrAYiyezdNbfW8fjBbpIY6YIlIIsCeRIRT9YMBQ2UY_DZKoTnMZtPTUnH1KHx6yf_Ie4E7UJMCyoNcqlzLNNT5Gp5gf1qlfol1TMa-HQz5oIAulZLAFy5e-dZYITrb5IGQFQreGGd0i04fQGFcuqxcic49672rwVcTrCvcJKYd5s0VVLchIPx'],
            ['cat' => 'kopi',    'name' => 'Cold Brew Classic',   'desc' => 'Kopi house blend diseduh 24 jam. Halus, kuat, dan menyegarkan.',     'price' => 52500, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCHNJXHRB9OMH9DvMVaeQuSNWfByn5QMKKI0i4lgqU_McNzc6KoMK6GwYkTHf4yLWaH3grCBwuMEKhCa_ru3xzf3bAE-J-tSYy2N0o20JvNR_0Zs0-_0EEfK5HaIX5YrxExkvBT9DU7AkzgZwiAVGEEi5m_e-Jx3IWS0TfvtDjlJqz9uK9PnbZrAl6ZwZAyVSS0JxCOnpEw9jJRM6PDFQ-v_Y7SKsdWISYUkogdqSgNAtbvr033Rs__EzN6ru5K_SnAx3veZnrrsM9z'],
            ['cat' => 'kopi',    'name' => 'Cappuccino Italia',   'desc' => 'Espresso klasik dengan foam susu yang tebal dan lembut.',             'price' => 45000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKbb-ii-5JXMfOSe4gnjdDxQ_ZzG7p88FeR45IwJMYs3t5ReVp-LCx87QDJ9nqNOe9fZohM04ghtFfISxa7RTJtUnM17ocevRnAsFoVw8Es7Sm2yYbflcDh5spRA3q73-n11EjRXOp4eINctb5oGeL1NnxTm1WI0Chff-2zoVE6jS7wZlw9ST9m-9RutOoqk-O295pnn9P0ZJN8JrQz4TpZSKxbbjiRNVAcvTBa-S4KRuhnbhLbzJx1cY5Al0QOAmhc5bSx5H1JlNg'],
            ['cat' => 'kopi',    'name' => 'Matcha Latte',        'desc' => 'Matcha premium Jepang dengan susu segar yang creamy.',                'price' => 48000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBT9PAG3x9TTRZJ_VWSwcirhm5GkIpO92RMRm8XMCcWuZ-QC-cA6kVJMITdAQo5QuyF9hGkqpW4hLj-N9JDujMgomkqrAYiyezdNbfW8fjBbpIY6YIlIIsCeRIRT9YMBQ2UY_DZKoTnMZtPTUnH1KHx6yf_Ie4E7UJMCyoNcqlzLNNT5Gp5gf1qlfol1TMa-HQz5oIAulZLAFy5e-dZYITrb5IGQFQreGGd0i04fQGFcuqxcic49672rwVcTrCvcJKYd5s0VVLchIPx'],
            ['cat' => 'kopi',    'name' => 'Americano',           'desc' => 'Espresso kuat dengan tambahan air panas, rasa murni kopi.',           'price' => 38000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCHNJXHRB9OMH9DvMVaeQuSNWfByn5QMKKI0i4lgqU_McNzc6KoMK6GwYkTHf4yLWaH3grCBwuMEKhCa_ru3xzf3bAE-J-tSYy2N0o20JvNR_0Zs0-_0EEfK5HaIX5YrxExkvBT9DU7AkzgZwiAVGEEi5m_e-Jx3IWS0TfvtDjlJqz9uK9PnbZrAl6ZwZAyVSS0JxCOnpEw9jJRM6PDFQ-v_Y7SKsdWISYUkogdqSgNAtbvr033Rs__EzN6ru5K_SnAx3veZnrrsM9z'],
            // 🍵 TEH & MINUMAN
            ['cat' => 'teh',     'name' => 'Jasmine Green Tea',   'desc' => 'Teh hijau segar dengan bunga melati pilihan, aroma harum dan menenangkan.', 'price' => 32000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBT9PAG3x9TTRZJ_VWSwcirhm5GkIpO92RMRm8XMCcWuZ-QC-cA6kVJMITdAQo5QuyF9hGkqpW4hLj-N9JDujMgomkqrAYiyezdNbfW8fjBbpIY6YIlIIsCeRIRT9YMBQ2UY_DZKoTnMZtPTUnH1KHx6yf_Ie4E7UJMCyoNcqlzLNNT5Gp5gf1qlfol1TMa-HQz5oIAulZLAFy5e-dZYITrb5IGQFQreGGd0i04fQGFcuqxcic49672rwVcTrCvcJKYd5s0VVLchIPx'],
            ['cat' => 'teh',     'name' => 'Thai Tea Klasik',     'desc' => 'Teh merah khas Thailand dengan susu kental manis yang creamy dan manis.', 'price' => 35000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCHNJXHRB9OMH9DvMVaeQuSNWfByn5QMKKI0i4lgqU_McNzc6KoMK6GwYkTHf4yLWaH3grCBwuMEKhCa_ru3xzf3bAE-J-tSYy2N0o20JvNR_0Zs0-_0EEfK5HaIX5YrxExkvBT9DU7AkzgZwiAVGEEi5m_e-Jx3IWS0TfvtDjlJqz9uK9PnbZrAl6ZwZAyVSS0JxCOnpEw9jJRM6PDFQ-v_Y7SKsdWISYUkogdqSgNAtbvr033Rs__EzN6ru5K_SnAx3veZnrrsM9z'],
            ['cat' => 'teh',     'name' => 'Lemon Iced Tea',      'desc' => 'Teh hitam segar dengan perasan lemon asli dan sedikit madu alami.',   'price' => 28000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKbb-ii-5JXMfOSe4gnjdDxQ_ZzG7p88FeR45IwJMYs3t5ReVp-LCx87QDJ9nqNOe9fZohM04ghtFfISxa7RTJtUnM17ocevRnAsFoVw8Es7Sm2yYbflcDh5spRA3q73-n11EjRXOp4eINctb5oGeL1NnxTm1WI0Chff-2zoVE6jS7wZlw9ST9m-9RutOoqk-O295pnn9P0ZJN8JrQz4TpZSKxbbjiRNVAcvTBa-S4KRuhnbhLbzJx1cY5Al0QOAmhc5bSx5H1JlNg'],
            ['cat' => 'teh',     'name' => 'Taro Milk Tea',       'desc' => 'Minuman talas ungu dengan susu segar, manis lembut dan berwarna cantik.', 'price' => 38000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBT9PAG3x9TTRZJ_VWSwcirhm5GkIpO92RMRm8XMCcWuZ-QC-cA6kVJMITdAQo5QuyF9hGkqpW4hLj-N9JDujMgomkqrAYiyezdNbfW8fjBbpIY6YIlIIsCeRIRT9YMBQ2UY_DZKoTnMZtPTUnH1KHx6yf_Ie4E7UJMCyoNcqlzLNNT5Gp5gf1qlfol1TMa-HQz5oIAulZLAFy5e-dZYITrb5IGQFQreGGd0i04fQGFcuqxcic49672rwVcTrCvcJKYd5s0VVLchIPx'],
            ['cat' => 'teh',     'name' => 'Chamomile Honey Tea', 'desc' => 'Teh chamomile hangat dengan madu asli, cocok untuk relaksasi.',        'price' => 30000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCHNJXHRB9OMH9DvMVaeQuSNWfByn5QMKKI0i4lgqU_McNzc6KoMK6GwYkTHf4yLWaH3grCBwuMEKhCa_ru3xzf3bAE-J-tSYy2N0o20JvNR_0Zs0-_0EEfK5HaIX5YrxExkvBT9DU7AkzgZwiAVGEEi5m_e-Jx3IWS0TfvtDjlJqz9uK9PnbZrAl6ZwZAyVSS0JxCOnpEw9jJRM6PDFQ-v_Y7SKsdWISYUkogdqSgNAtbvr033Rs__EzN6ru5K_SnAx3veZnrrsM9z'],
            // 🥐 PASTRI
            ['cat' => 'pastri',  'name' => 'Almond Croissant',    'desc' => 'Croissant mentega renyah isi krim almond, dipanggang hangat setiap pagi.', 'price' => 42000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBmdu6nWWkMf9Kbq5bM4zp79Y0NzFNhufecO6uG6m8M8RsKiVj8GNSJ3wqqCPotyTCWWNRLPYzkEsQsQncsrs_7lX9EnY2C2hSsTBP34o5gbvYCJox3mm7IVTowMJAIqtKfbSHSUB5Tl45Y9Ub-UX3tzK6VM-kmhpyJXhOorzszx9PhgEZBQ-u_GK6g3VHIJ7Nz00AM2OcsrDN96DNgP6lf1jy2zOiekYpW0CXxj8yPpvQTN4EQOjioXVMJEYMsG83N-USlVWBaQUbX'],
            ['cat' => 'pastri',  'name' => 'Chocolate Muffin',    'desc' => 'Muffin cokelat lembut dengan chips cokelat yang meleleh di dalam.',    'price' => 35000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKbb-ii-5JXMfOSe4gnjdDxQ_ZzG7p88FeR45IwJMYs3t5ReVp-LCx87QDJ9nqNOe9fZohM04ghtFfISxa7RTJtUnM17ocevRnAsFoVw8Es7Sm2yYbflcDh5spRA3q73-n11EjRXOp4eINctb5oGeL1NnxTm1WI0Chff-2zoVE6jS7wZlw9ST9m-9RutOoqk-O295pnn9P0ZJN8JrQz4TpZSKxbbjiRNVAcvTBa-S4KRuhnbhLbzJx1cY5Al0QOAmhc5bSx5H1JlNg'],
            ['cat' => 'pastri',  'name' => 'Blueberry Scone',     'desc' => 'Scone tradisional Inggris dengan blueberry segar dan taburan gula.',  'price' => 38000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBT9PAG3x9TTRZJ_VWSwcirhm5GkIpO92RMRm8XMCcWuZ-QC-cA6kVJMITdAQo5QuyF9hGkqpW4hLj-N9JDujMgomkqrAYiyezdNbfW8fjBbpIY6YIlIIsCeRIRT9YMBQ2UY_DZKoTnMZtPTUnH1KHx6yf_Ie4E7UJMCyoNcqlzLNNT5Gp5gf1qlfol1TMa-HQz5oIAulZLAFy5e-dZYITrb5IGQFQreGGd0i04fQGFcuqxcic49672rwVcTrCvcJKYd5s0VVLchIPx'],
            ['cat' => 'pastri',  'name' => 'Cinnamon Roll',       'desc' => 'Roti gulung kayu manis dengan frosting krim vanilla yang melimpah.',   'price' => 45000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCHNJXHRB9OMH9DvMVaeQuSNWfByn5QMKKI0i4lgqU_McNzc6KoMK6GwYkTHf4yLWaH3grCBwuMEKhCa_ru3xzf3bAE-J-tSYy2N0o20JvNR_0Zs0-_0EEfK5HaIX5YrxExkvBT9DU7AkzgZwiAVGEEi5m_e-Jx3IWS0TfvtDjlJqz9uK9PnbZrAl6ZwZAyVSS0JxCOnpEw9jJRM6PDFQ-v_Y7SKsdWISYUkogdqSgNAtbvr033Rs__EzN6ru5K_SnAx3veZnrrsM9z'],
            ['cat' => 'pastri',  'name' => 'Banana Walnut Bread', 'desc' => 'Roti pisang lembab dengan topping walnut panggang, camilan favorit.',  'price' => 40000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBmdu6nWWkMf9Kbq5bM4zp79Y0NzFNhufecO6uG6m8M8RsKiVj8GNSJ3wqqCPotyTCWWNRLPYzkEsQsQncsrs_7lX9EnY2C2hSsTBP34o5gbvYCJox3mm7IVTowMJAIqtKfbSHSUB5Tl45Y9Ub-UX3tzK6VM-kmhpyJXhOorzszx9PhgEZBQ-u_GK6g3VHIJ7Nz00AM2OcsrDN96DNgP6lf1jy2zOiekYpW0CXxj8yPpvQTN4EQOjioXVMJEYMsG83N-USlVWBaQUbX'],
            // 🍳 SARAPAN
            ['cat' => 'sarapan', 'name' => 'Avocado Toast',       'desc' => 'Roti sourdough panggang dengan alpukat segar, telur poached, dan biji wijen.', 'price' => 55000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKbb-ii-5JXMfOSe4gnjdDxQ_ZzG7p88FeR45IwJMYs3t5ReVp-LCx87QDJ9nqNOe9fZohM04ghtFfISxa7RTJtUnM17ocevRnAsFoVw8Es7Sm2yYbflcDh5spRA3q73-n11EjRXOp4eINctb5oGeL1NnxTm1WI0Chff-2zoVE6jS7wZlw9ST9m-9RutOoqk-O295pnn9P0ZJN8JrQz4TpZSKxbbjiRNVAcvTBa-S4KRuhnbhLbzJx1cY5Al0QOAmhc5bSx5H1JlNg'],
            ['cat' => 'sarapan', 'name' => 'Big Breakfast',       'desc' => 'Telur orak-arik, sosis, bacon, jamur, dan toast — sarapan lengkap!',   'price' => 75000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBT9PAG3x9TTRZJ_VWSwcirhm5GkIpO92RMRm8XMCcWuZ-QC-cA6kVJMITdAQo5QuyF9hGkqpW4hLj-N9JDujMgomkqrAYiyezdNbfW8fjBbpIY6YIlIIsCeRIRT9YMBQ2UY_DZKoTnMZtPTUnH1KHx6yf_Ie4E7UJMCyoNcqlzLNNT5Gp5gf1qlfol1TMa-HQz5oIAulZLAFy5e-dZYITrb5IGQFQreGGd0i04fQGFcuqxcic49672rwVcTrCvcJKYd5s0VVLchIPx'],
            ['cat' => 'sarapan', 'name' => 'Granola Bowl',        'desc' => 'Granola renyah dengan Greek yogurt, madu, dan buah segar pilihan.',   'price' => 52000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCHNJXHRB9OMH9DvMVaeQuSNWfByn5QMKKI0i4lgqU_McNzc6KoMK6GwYkTHf4yLWaH3grCBwuMEKhCa_ru3xzf3bAE-J-tSYy2N0o20JvNR_0Zs0-_0EEfK5HaIX5YrxExkvBT9DU7AkzgZwiAVGEEi5m_e-Jx3IWS0TfvtDjlJqz9uK9PnbZrAl6ZwZAyVSS0JxCOnpEw9jJRM6PDFQ-v_Y7SKsdWISYUkogdqSgNAtbvr033Rs__EzN6ru5K_SnAx3veZnrrsM9z'],
            ['cat' => 'sarapan', 'name' => 'French Toast',        'desc' => 'Roti tebal dicelup telur dan digoreng, disajikan dengan sirup maple.',  'price' => 48000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBmdu6nWWkMf9Kbq5bM4zp79Y0NzFNhufecO6uG6m8M8RsKiVj8GNSJ3wqqCPotyTCWWNRLPYzkEsQsQncsrs_7lX9EnY2C2hSsTBP34o5gbvYCJox3mm7IVTowMJAIqtKfbSHSUB5Tl45Y9Ub-UX3tzK6VM-kmhpyJXhOorzszx9PhgEZBQ-u_GK6g3VHIJ7Nz00AM2OcsrDN96DNgP6lf1jy2zOiekYpW0CXxj8yPpvQTN4EQOjioXVMJEYMsG83N-USlVWBaQUbX'],
            ['cat' => 'sarapan', 'name' => 'Pancake Stack',       'desc' => 'Tumpukan pancake fluffy 3 lapis dengan butter, sirup maple, dan buah.', 'price' => 58000, 'img' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKbb-ii-5JXMfOSe4gnjdDxQ_ZzG7p88FeR45IwJMYs3t5ReVp-LCx87QDJ9nqNOe9fZohM04ghtFfISxa7RTJtUnM17ocevRnAsFoVw8Es7Sm2yYbflcDh5spRA3q73-n11EjRXOp4eINctb5oGeL1NnxTm1WI0Chff-2zoVE6jS7wZlw9ST9m-9RutOoqk-O295pnn9P0ZJN8JrQz4TpZSKxbbjiRNVAcvTBa-S4KRuhnbhLbzJx1cY5Al0QOAmhc5bSx5H1JlNg'],
        ];

        foreach ($menuItems as $item) {
            Menu::create([...$item, 'is_active' => true]);
        }
    }
}
